menu:
    About: /2016/03/18/About/
    Twitter: https://twitter.com/hkalexling
    GitHub: https://github.com/hkalexling

favicon: /favicon.ico
logo: https://pbs.twimg.com/profile_images/710182904517632000/5hqFB3RR.jpg

# Comment
# e.g disqus: seansun
disqus: yunolab

# Analytics
# google-analytics:
ga: UA-66085745-2

# Copyright Infomation
startyear: 2015
